# name: React App CI

# on: [push]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x, 16.x]

#     steps:
#     - uses: actions/checkout@v2

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}

#     - name: Change to React app directory
#       run: cd fleetmanagementclient

#     - name: Install dependencies
#       run: npm install
#       working-directory: ./fleetmanagementclient

#     - name: Run tests
#       run: npm test
#       working-directory: ./fleetmanagementclient
